// <auto-generated />
namespace PostEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class idCa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idCa));
        
        string IMigrationMetadata.Id
        {
            get { return "201807062108169_idCa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
